<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Edit Form</title>
</head>
<body>
	<form action="Edit" method="POST" enctype="multipart/form-data">
	<fieldset>
        <legend>Edit your product:</legend>
        <input type="hidden" name="id" value="<?php echo $args[0]['product_id'] ?>">
		Product name:<br>
		<input type="text" name="new_product_name" value="<?php echo $args[0]['product_name'] ?>" >
		<br>
		Price:<br>
		<input type="text" name="new_price" value="<?php echo $args[0]['price'] ?>" >
		<br><br>
		<div style="padding: 10px 0px">Edit Product Image</div>
		<input type="file" name="new_image" ><br>
		<br>
		<button type="submit" name="edited">Edit</button>
	</fieldset>
</form>
</body>
</html>