<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Search Form</title>
</head>
<body>
	<form class="form" action="Filter" method="POST">
		<div class="name">Name:</div>
		<input type="text" name="s_name" placeholder="Search Name">
		<div class="id">ID:</div>
		<input type="text" name="s_from_id" placeholder="From Product ID">
		<input type="text" name="s_to_id" placeholder="To Product ID">
		<div class="price">Price:</div>
		<input type="text" name="s_from_price" placeholder="From Price">
		<input type="text" name="s_to_price" placeholder="To Price">
		<input type="submit" name="submit" value="Accept filter">
	</form>
</body>
</html>