<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Add Product</title>
</head>
<body>
	<form action="Add" method="POST" enctype="multipart/form-data">
	  	<fieldset>
		    <legend>Create your product:</legend>
		    Product name:<br>
		    <input type="text" name="Product_name" placeholder="Product name">
		    <br>
		    Price:<br>
		    <input type="text" name="Price" placeholder="Price">
		    <br><br>
		    <div style="padding: 10px 0px">Product Image</div>
		    <input type="file" name="image"><br>
		    <br>
		    <button type="submit" name="submit">UPLOAD</button>
	  	</fieldset>
	</form>
</body>
</html>