<?php 
	//var_dump($args);
	/*$count = count($args[0]);
	for ($row = 0; $row < count($args); $row++) {
	  echo "<p><b>Row number $row</b></p>";
	  echo "<ul>";
	  //for ($col = 0; $col < $count; $col++) {
	  		echo "<li> Product id: ".$args[$row]['product_id']."</li>";
	  		echo "<li>". $args[$row]['product_name'] ."</li>";
	  		echo "<li>".$args[$row]['price']."</li>";
	  		echo "<li><img src=/image/".$args[$row]['image']."></li>";
	  	//}
	  echo "</ul>"; 
	  }
	  

	echo '<button><a href="Add">Add</a></button>';*/
?>
<html>
	<head>
		<title>Display Image</title>
		<link rel="stylesheet" href="css/index.css">
		<script src="js/jquery-3.4.1.js"></script>
		<script src="js/index.js"></script>
		<script>
			$(function() {
				$("#addSubmit").click(function(event) {
					var product_id = $('#Product_id').val();
					var product_name = $('#Product_name').val();
					var price = $('#Price').val();
					$.ajax({
						url: 'add',
						type: 'POST',
						contentType: "application/json",
						dataType: 'json',
						data:JSON.stringify(
						{
							"p_name": product_name,
							"p_price": price
						})
					})
					.done(function(data) {
						console.log(data);
						var display = '';
						$.each(data, function(key, value) {
							display += '<tr class="row">';
							display += '<td>'+ value.product_id + '</td>';
							display += '<td>'+ value.product_name + '</td>';
							display += '<td>'+ value.price + '</td>';
							display += '<td><img src ="image/'+ value.image + '"></td>';
							display += '<td><a href="Edit?' + value.product_id + '">Edit</a></td>';
							display += '<td><input type="button" onClick="deleteme('+ value.product_id + ')" class="delete" value="Delete"></td>';
							display += '</tr>';
							
						});
						$(".row").replaceWith(display);
						//console.log(display);
					})
				});
			});
		</script>
	</head>
	<body>
		<div class="logout"><a href="">Logout</a></div>
		<div class="add">Add</div>
		<div class="filter"><a href="Filter">Filter</a></div>
		<table class="dataTable" id="dataTable">
			<thead>
				<tr>
					<th>Product ID</th>
					<th>Product Name</th>
					<th>Price</th>
					<th>Image</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			</thead>
			<?php
				for ($row = 0; $row < count($args); $row++){
					?>
						<tr class="row" id="tableRow" >
							<td id="product_id">
								<?php echo $args[$row]['product_id']?>
							</td>
							<td id="product_name">
								<?php echo $args[$row]['product_name'];?>
							</td>
							<td id="price">
								<?php echo $args[$row]['price'];?>
							</td>
							<td id="image">
								<?php echo '<img src ="image/'.$args[$row]['image'].'">'; ?>
							</td>
							<td>
								<?php echo '<a href="Edit?'. $args[$row]['product_id'] . '">Edit</a>';?> 
							</td>
							<td>
								<?php 
									echo '<input type="button" onClick="deleteme('. $args[$row]['product_id'] .')" class="delete" value="Delete">';
								?>
							</td>
						</tr>
						<script language="javascript">
							function deleteme(delid){
								if(confirm("Do you want to delete?")){
									window.location.href = "Delete?" + delid;
									return true;
								}
							}
						</script>

					<?php
				}
			?>
		</table>
		<div class="nenden"></div>
		<form class="form" id="formAdd" enctype="multipart/form-data">
			<fieldset>
				<legend>Create your product:</legend>
				<input type="hidden" id="Product_id" >
				Product name:<br>
				<input type="text" id="Product_name" placeholder="Product name" required="Empty">
				<br>
				Price:<br>
				<input type="text" id="Price" placeholder="Price" required="Empty">
				<br><br>
				<div style="padding: 10px 0px">Product Image</div>
				<input type="file" name="image"><br>
				<br>
				<button type="button" id="addSubmit">UPLOAD</button>
			</fieldset>
		</form>
	</body>
</html>
