<?php 
	//var_dump($args);
	/*$count = count($args[0]);
	for ($row = 0; $row < count($args); $row++) {
	  echo "<p><b>Row number $row</b></p>";
	  echo "<ul>";
	  //for ($col = 0; $col < $count; $col++) {
	  		echo "<li> Product id: ".$args[$row]['product_id']."</li>";
	  		echo "<li>". $args[$row]['product_name'] ."</li>";
	  		echo "<li>".$args[$row]['price']."</li>";
	  		echo "<li><img src=/image/".$args[$row]['image']."></li>";
	  	//}
	  echo "</ul>"; 
	  }
	  

	echo '<button><a href="Add">Add</a></button>';*/
?>
<html>
	<head>
		<title>Display Image</title>
		<style>
			*{margin: 0px; padding: 0px;}

			.delete{
			    color: blue;
			    cursor: pointer;
			}

			.no {
			    display: inline-block;
			    padding: 15px;
			    border: 1px solid black;
			    border-radius: 15px;
			    background: lightskyblue;
			    color: white;
			    cursor: pointer;
			    margin: 15px 25px;
			}

			.no:hover {
			    background: blue;
			}

			.yes {
			    display: inline-block;
			    padding: 15px;
			    border: 1px solid black;
			    border-radius: 15px;
			    background: red;
			    color: white;
			    cursor: pointer;
			    margin: 15px 36px;
			}

			.yes:hover {
			    background: mediumvioletred;
			}

			.chuto {
			    text-align: center;
			    font-size: 25px;
			    padding-top: 30px;
			    color: red;
			}

			.nenden {
			    background: black;
			    opacity: 0.4;
			    position: fixed;
			    top: 0px;
			    left: 0px;
			    width: 100%;
			    height: 100%;
			    visibility: hidden;
			}

			.khung {
			    width: 250px;
			    height: 150px;
			    position: absolute;
			    top: 50%;
			    left: 42%;
			    background: aliceblue;
			    border: 1px solid black;
			    visibility: hidden;
			}

			.add a {
			    padding: 15px;
			    border: 1px solid black;
			    text-decoration: none;
			    color: greenyellow;
			    background: sandybrown;
			    border-radius: 15px;
			    position: fixed;
			    top: 95px;
			    right: 33px;
			}

			.add:hover a {
			    background: black;
			    cursor: pointer;
			}

			.logout a {
			    padding: 15px;
			    border: 1px solid black;
			    border-radius: 50px;
			    background: red;
			    text-decoration: none;
			    color: white;
			    position: fixed;
			    top: 25px;
			    right: 25px;
			}

			.logout:hover a {
			    background: aquamarine;
			}

			.row a {
			    text-decoration: none;
			    color: blue;
			    cursor: pointer;
			}

			.paging {
			    left: 47%;
			    position: fixed;
			    bottom: 0px;
			    display: inline-block;
			}

			.paging a {
			    padding: 10px;
			    border: 1px solid blue;
			    text-align: center;
			    text-decoration: none;
			}

			th {
			    border: 1px solid black;
			    border-collapse: collapse;
			    color: white;
			    background: #5b5b5b;
			}

			.row {
			    width: 100px;
			    height: 100px;
			}

			.row td {
			    height: 200px;
			    width: 200px;
			    text-align: center;
			    border: 1px solid;
			    border-collapse: collapse;
			}

			.row td img {
			    width: 100px;
			    height: 100px;
			}

			table {
			    margin: auto;
			}

			.active{
			    visibility: visible;
			}

			.filter a{
			    padding: 15px;
			    border: 1px solid black;
			    text-decoration: none;
			    color: greenyellow;
			    background: sandybrown;
			    border-radius: 15px;
			    position: fixed;
			    top: 160px;
			    right: 30px;
			}

			.filter:hover a{
			    background: black;
			    cursor: pointer;
			}

			.form {
			    background: wheat;
			    padding: 10px;
			    border: 1px solid;
			    width: 350px;
			    position: fixed;
			    top: 35%;
			    left: 35%;
			    transition: 0.4s;
			    transform: scale(0.5);
			    visibility: hidden;
			}

			.active1{
			    visibility: visible;
			    transform: scale(1);
			}
		</style>
	</head>
	<body>
		<div class="logout"><a href="">Logout</a></div>
		<div class="add"><a href="Add">Add</a></div>
		<div class="filter"><a href="Filter">Filter</a></div>
		<table>
			<thead>
				<tr>
					<th>Product ID</th>
					<th>Product Name</th>
					<th>Price</th>
					<th>Image</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			</thead>
			<?php
				for ($row = 0; $row < count($args); $row++){
					?>
						<tr class="row" id=<?php echo $args[$row]['product_id']?> >
							<td>
								<?php echo $args[$row]['product_id']?>
							</td>
							<td>
								<?php echo $args[$row]['product_name'];?>
							</td>
							<td>
								<?php echo $args[$row]['price'];?>
							</td>
							<td>
								<?php echo '<img src ="image/'.$args[$row]['image'].'">'; ?>
							</td>
							<td>
								<?php echo '<a href="Edit?'. $args[$row]['product_id'] . '">Edit</a>';?> 
							</td>
							<td>
								<?php 
									echo '<input type="button" onClick="deleteme('. $args[$row]['product_id'] .')" class="delete" value="Delete">';
								?>
							</td>
						</tr>
						<script language="javascript">
							function deleteme(delid){
								if(confirm("Do you want to delete?")){
									window.location.href = "Delete?" + delid;
									return true;
								}
							}
						</script>

					<?php
				}
			?>
